#include "pch.h"
#include "Microsoft.Xbox.Services.Privacy.PermissionIdConstants.h"
#include "Microsoft.Xbox.Services.Privacy.PermissionIdConstants.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
////////

namespace winrt::Microsoft::Xbox::Services::Privacy::implementation
{
    hstring PermissionIdConstants::CommunicateUsingText()
    {
        printf("PermissionIdConstants::CommunicateUsingText\n");
        return L"";
    }
    hstring PermissionIdConstants::CommunicateUsingVideo()
    {
        printf("PermissionIdConstants::CommunicateUsingVideo\n");
        return L"";
    }
    hstring PermissionIdConstants::CommunicateUsingVoice()
    {
        printf("PermissionIdConstants::CommunicateUsingVoice\n");
        return L"";
    }
    hstring PermissionIdConstants::ViewTargetProfile()
    {
        printf("PermissionIdConstants::ViewTargetProfile\n");
        return L"";
    }
    hstring PermissionIdConstants::ViewTargetGameHistory()
    {
        printf("PermissionIdConstants::ViewTargetGameHistory\n");
        return L"";
    }
    hstring PermissionIdConstants::ViewTargetVideoHistory()
    {
        printf("PermissionIdConstants::ViewTargetVideoHistory\n");
        return L"";
    }
    hstring PermissionIdConstants::ViewTargetMusicHistory()
    {
        printf("PermissionIdConstants::ViewTargetMusicHistory\n");
        return L"";
    }
    hstring PermissionIdConstants::ViewTargetExerciseInfo()
    {
        printf("PermissionIdConstants::ViewTargetExerciseInfo\n");
        return L"";
    }
    hstring PermissionIdConstants::ViewTargetPresence()
    {
        printf("PermissionIdConstants::ViewTargetPresence\n");
        return L"";
    }
    hstring PermissionIdConstants::ViewTargetVideoStatus()
    {
        printf("PermissionIdConstants::ViewTargetVideoStatus\n");
        return L"";
    }
    hstring PermissionIdConstants::ViewTargetMusicStatus()
    {
        printf("PermissionIdConstants::ViewTargetMusicStatus\n");
        return L"";
    }
    hstring PermissionIdConstants::PlayMultiplayer()
    {
        printf("PermissionIdConstants::PlayMultiplayer\n");
        return L"";
    }
    hstring PermissionIdConstants::BroadcastWithTwitch()
    {
        printf("PermissionIdConstants::BroadcastWithTwitch\n");
        return L"";
    }
    hstring PermissionIdConstants::ViewTargetUserCreatedContent()
    {
        printf("PermissionIdConstants::ViewTargetUserCreatedContent\n");
        return L"";
    }
}
